name: CI
'on':
  workflow_dispatch: {}
  release:
    types:
    - published
  push:
    branches:
    - main
  pull_request: {}
  create: {}
jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      id: get-token
      run: echo "token=$(./get-github-app-token.sh)" >> $GITHUB_OUTPUT
      env:
        APP_SECRET: ${{ secrets.APP_SECRET }}
        APP_ID: ${{ secrets.APP_ID }}
        GH_REPO: ${{ github.repository }}
    - name: print token
      run: echo "${{ steps.outputs.get-token }}"
