name: CI
'on':
  workflow_dispatch: {}
  release:
    types:
    - published
  push:
    branches:
    - main
  pull_request: {}
  create: {}
jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    # - name: my-step
      # id: my-step
      # run: |
      #   output=$(.github/workflows/echo.sh)
      #   echo "my_second_output=$output" >> $GITHUB_OUTPUT

    - name: Generate Github App Token
      id: generate-token
      uses: khajavi/generate-github-app-token@v0.0.7
      with:
        app_id: ${{ secrets.APP_ID }}
        app_private_key: ${{ secrets.APP_SECRET }}

    - name: print-output
      run: |
        echo "Output of token: ${{ steps.generate-token.outputs.token }}"
        echo "Output of my-token: ${{ steps.generate-token.outputs.token }}"

    # - name: Get Token
    #   id: get-token
    #   run: |
    #     output=$(.github/workflows/get-github-app-token.sh)
    #     echo "my_token=$output" >> $GITHUB_OUTPUT
    #   env:
    #     APP_SECRET: ${{ secrets.APP_SECRET }}
    #     APP_ID: ${{ secrets.APP_ID }}
    #     GH_REPO: ${{ github.repository }}
    - name: print token
      run: |
        echo "token: ${{ steps.generate-token.outputs.token }}"
    - name: Publish example file
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        echo "This is an example file." > example.txt
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b my-feature-branch
        git add example.txt
        git commit -m "Add example file"
        git push origin my-feature-branch --force
    - name: Create PR
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        gh pr create \
          --title "New feature" \
          --body "This pull request adds a new feature" \
          --base main \
          --head my-feature-branch