name: CI
'on':
  workflow_dispatch: {}
  release:
    types:
    - published
  push:
    branches:
    - main
  pull_request: {}
  create: {}
jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Get Token
      id: get-token
      run: |
        ls -laR 
        echo "token=$(.github/workflows/get-github-app-token.sh)" >> $GITHUB_OUTPUT
      env:
        APP_SECRET: ${{ secrets.APP_SECRET }}
        APP_ID: ${{ secrets.APP_ID }}
        GH_REPO: ${{ github.repository }}
    - name: print token
      run: echo "${{ steps.outputs.get-token }}"
    - name: Create PR
      run: |
        gh pr create \
          --title "New feature" \
          --body "This pull request adds a new feature" \
          --base main \
          --head feature-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}