name: CI
'on':
  workflow_dispatch: {}
  release:
    types:
    - published
  push:
    branches:
    - main
  pull_request: {}
  create: {}
jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Get Token
      id: get-token
      run: |
        ls -laR 
        echo "token=$(.github/workflows/get-github-app-token.sh)" >> $GITHUB_OUTPUT
        echo "my-token=hello" >> $GITHUB_OUTPUT
      env:
        APP_SECRET: ${{ secrets.APP_SECRET }}
        APP_ID: ${{ secrets.APP_ID }}
        GH_REPO: ${{ github.repository }}
    - name: print token
      run: echo "token: ${{ steps.outputs.get-token.token }}"
      run: echo "my-token: ${{ steps.outputs.get-token.my-token }}"
    - name: Publish example file
      run: |
        echo "This is an example file." > example.txt
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b my-feature-branch
        git add example.txt
        git commit -m "Add example file"
        git push origin my-feature-branch --force
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
    - name: Create PR
      run: |
        gh pr create \
          --title "New feature" \
          --body "This pull request adds a new feature" \
          --base main \
          --head my-feature-branch
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}