name: CI
'on':
  workflow_dispatch: {}
  release:
    types:
    - published
  push:
    branches:
    - main
  pull_request: {}
  create: {}
jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: my-step
      id: my-step
      run: |
        output=$(.github/workflows/echo.sh)
        echo "my_second_output=$output" >> $GITHUB_OUTPUT
    
    - name: print-output
      run: |
        echo "Output of my-step: ${{ steps.my-step.outputs.my_second_output }}"

    - name: Get Token
      id: get-token
      run: |
        output=$(.github/workflows/get-github-app-token.sh)
        echo "my_token=$output" >> $GITHUB_OUTPUT
      env:
        APP_SECRET: ${{ secrets.APP_SECRET }}
        APP_ID: ${{ secrets.APP_ID }}
        GH_REPO: ${{ github.repository }}
    - name: print token
      run: |
        echo "token: ${{ steps.get-token.outputs.my_token }}"
    - name: Publish example file
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.my_token }}
      run: |
        echo "This is an example file." > example.txt
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b my-feature-branch
        git add example.txt
        git commit -m "Add example file"
        git push origin my-feature-branch --force
    - name: Create PR
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.my_token }}
      run: |
        gh pr create \
          --title "New feature" \
          --body "This pull request adds a new feature" \
          --base main \
          --head my-feature-branch